# SPDX-FileCopyrightText: 2026 Iain Lane <iain@orangesquash.org.uk>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# logfilename                 [owner:group]  mode  count  size  when  flags
/var/log/procps-helperd.log   root:admin     640   5      1024  *     BN
